name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  repository_dispatch:
    types: [response-time]
  workflow_dispatch:
jobs:
  response-time:
    name: Check response time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Check response time
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
